name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://prep.comptia.org/
            https://prep.comptia.org/en-us/
            https://prep.comptia.org/en/training/
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true